// defaultTo.test.js
// These tests were generated by an AI without modifying them after
import defaultTo from "../src/defaultTo";

describe("defaultTo by AI", () => {
  test("returns the value when it is a valid number", () => {
    expect(defaultTo(1, 10)).toBe(1);
    expect(defaultTo(0, 10)).toBe(0); // 0 is a valid value, not defaulted
  });

  test("returns the default when value is undefined", () => {
    expect(defaultTo(undefined, 10)).toBe(10);
  });

  test("returns the default when value is null", () => {
    expect(defaultTo(null, 10)).toBe(10);
  });

  test("returns the default when value is NaN", () => {
    expect(defaultTo(NaN, 10)).toBe(10);
    // Ensure Number.isNaN check works, not string "NaN"
    expect(defaultTo("NaN", 10)).toBe("NaN"); // string is not NaN
  });

  test("works with strings", () => {
    expect(defaultTo("hello", "default")).toBe("hello");
    expect(defaultTo("", "default")).toBe(""); // empty string is a valid value
  });

  test("works with booleans", () => {
    expect(defaultTo(true, false)).toBe(true);
    expect(defaultTo(false, true)).toBe(false);
  });

  test("works with objects and arrays", () => {
    const obj = { a: 1 };
    const arr = [1, 2, 3];
    expect(defaultTo(obj, { b: 2 })).toBe(obj);
    expect(defaultTo(arr, [])).toBe(arr);
  });

  test("works with symbols and bigints", () => {
    const sym = Symbol("x");
    const big = BigInt(123);
    expect(defaultTo(sym, Symbol("y"))).toBe(sym);
    expect(defaultTo(big, BigInt(0))).toBe(big);
  });

  test("returns default when defaultValue is undefined and value is nullish/NaN", () => {
    expect(defaultTo(undefined, undefined)).toBe(undefined);
    expect(defaultTo(null, undefined)).toBe(undefined);
    expect(defaultTo(NaN, undefined)).toBe(undefined);
  });

  test("does not coerce other falsy values to default", () => {
    // Falsy but valid values should not trigger default
    expect(defaultTo("", "x")).toBe("");
    expect(defaultTo(0, 1)).toBe(0);
    expect(defaultTo(false, true)).toBe(false);
  });
});
